### ISSUE TITLE
Please contrast DistT with State monad

### ISSUE THREAD

**Issue by benhutchison** [armanbilge/schrodinger#3]
A classic approach to deterministic randomness in functional programs is to thread a PRNG seed through a program using a state monad. 

When I came to the schrondinger project, I was looking to understand `DistT` in terms of how it aligns and or differs from that approach. Some commentary in the README may help others with a similar background to understand your approach.

**Comment by armanbilge** [comment]
Thanks for your interested in the project and raising this issue! It prompted me to revisit my initial design choices. Does the documentation for the new `RandomT` added in #4 provide the explanation that you were looking for?

Some additional notes:

The original `DistT[F[_], A]` was internally very similar to Cat's `StateT[F[_], S, A]` monad transformer. However, I was able to drop the type parameter `S` (which I felt was cumbersome) by assuming an RNG implementing the `Generator` trait would be provided at time of sampling. This had the added benefit of making all `DistT`s agnostic to the choice of RNG implementation.

In #4 I reimplemented `DistT` as `RandomT[F[_], S, A]` which is essentially a light wrapper around `StateT` (wrapping is necessary so that `RandomT` can have its own typeclass implementations). Although the `S` is back (shifting the burden to users to write RNG-generic code) I realized that it enables much more modularity: specifically, `RandomT[F, S, A]` can derive its typeclasses from those available for `S`.

For example, to support Cats Effect's `Async` typeclass and friends required an RNG capable of "splitting" into two streams. Previously, `DistT` required all generators to support this (even if you are not writing `Async` code!). For the new `RandomT`, `Async` instances are available only if `S` has a `Split` typeclass available; if not, you can still use `RandomT` with your non-splittable RNG but you are constrained to "vanilla" typeclasses (monad and friends).
